globalThis.WEAVE_COMPARISONS = {
  finance: {
    tab: "Board forecast",
    label: "Finance review",
    title: "Publish a forecast the board can trace",
    task: "Turn actuals, budget, and planning assumptions into a reconciled model and a short variance narrative.",
    codex: {
      goal: "Build the forecast pack from the supplied workbook.",
      route: ["Inspect files", "Choose analysis", "Create outputs", "Decide when done"],
      note: "Codex can adapt freely, but the order of analysis, evidence threshold, and retry point are decided inside the run unless the prompt spells them out.",
    },
    nodes: [
      { id: "source", kind: "input", eyebrow: "FILES", title: "Actuals + budget", x: 20, y: 151 },
      { id: "assumptions", kind: "human", eyebrow: "CALIBRATE", title: "Lock assumptions", x: 210, y: 50 },
      { id: "integrity", kind: "check", eyebrow: "EXACT CHECK", title: "Validate sources", x: 210, y: 252 },
      { id: "model", kind: "work", eyebrow: "CODEX", title: "Build forecast", x: 400, y: 50 },
      { id: "variance", kind: "work", eyebrow: "CODEX", title: "Explain variance", x: 400, y: 252 },
      { id: "reconcile", kind: "check", eyebrow: "EXACT CHECK", title: "Reconcile totals", x: 590, y: 151 },
      { id: "exceptions", kind: "human", eyebrow: "CALIBRATE", title: "Review exceptions", x: 780, y: 50 },
      { id: "publish", kind: "verify", eyebrow: "DELIVER", title: "Board pack", x: 780, y: 252 },
    ],
    edges: [
      ["source", "assumptions"], ["source", "integrity"], ["assumptions", "model"],
      ["integrity", "variance"], ["model", "reconcile"], ["variance", "reconcile"],
      ["reconcile", "exceptions"], ["exceptions", "publish"],
      { from: "reconcile", to: "model", kind: "recovery", label: "mismatch" },
    ],
    contracts: {
      evidence: "Actuals, budget, and every changed assumption",
      calibration: "Finance locks materiality and scenario assumptions",
      check: "Model totals must reconcile to source rows",
      recovery: "A mismatch returns to Build forecast, not the final memo",
    },
    result: "The analyst chooses the order, the sign-off point, and exactly where a failed reconciliation returns.",
  },
  campaign: {
    tab: "Campaign launch",
    label: "Creative production",
    title: "Explore broadly, then hold one visual direction",
    task: "Create a launch poster and social crop from fixed event facts, with an intentional review loop before export.",
    codex: {
      goal: "Create the campaign assets from the brand pack.",
      route: ["Read brief", "Choose direction", "Make assets", "Review output"],
      note: "A single prompt leaves concept selection, review timing, and which artifact to revise inside the adaptive run.",
    },
    nodes: [
      { id: "brief", kind: "input", eyebrow: "BRIEF", title: "Facts + brand", x: 20, y: 151 },
      { id: "concepts", kind: "work", eyebrow: "CODEX", title: "Explore 3 concepts", x: 210, y: 151 },
      { id: "direction", kind: "human", eyebrow: "CALIBRATE", title: "Choose direction", x: 400, y: 50 },
      { id: "poster", kind: "work", eyebrow: "CODEX", title: "Render poster", x: 400, y: 252 },
      { id: "social", kind: "work", eyebrow: "CODEX", title: "Build social crop", x: 590, y: 50 },
      { id: "facts", kind: "check", eyebrow: "EXACT CHECK", title: "Check facts + sizes", x: 590, y: 252 },
      { id: "critique", kind: "human", eyebrow: "CALIBRATE", title: "Critique hierarchy", x: 780, y: 50 },
      { id: "export", kind: "verify", eyebrow: "DELIVER", title: "Export asset set", x: 780, y: 252 },
    ],
    edges: [
      ["brief", "concepts"], ["concepts", "direction"], ["direction", "poster"],
      ["direction", "social"], ["poster", "facts"], ["social", "facts"],
      ["facts", "critique"], ["critique", "export"],
      { from: "critique", to: "poster", kind: "recovery", label: "revise" },
    ],
    contracts: {
      evidence: "Brand files, exact event facts, and chosen concept",
      calibration: "The creative lead selects one direction before rendering",
      check: "Names, date, venue, dimensions, contrast, and alt text",
      recovery: "A weak hierarchy returns only the poster to revision",
    },
    result: "Creative freedom stays inside deliberate concept, production, and critique stages chosen by the user.",
  },
  vendor: {
    tab: "Vendor decision",
    label: "Procurement analysis",
    title: "Separate hard constraints from subjective weighting",
    task: "Shortlist a CRM using primary evidence, operating requirements, and a sensitivity check on the final ranking.",
    codex: {
      goal: "Research the options and recommend a CRM.",
      route: ["Gather evidence", "Apply criteria", "Compare vendors", "Write recommendation"],
      note: "Codex chooses how much research is enough and when scoring assumptions are stable inside the run unless those decisions are externalized.",
    },
    nodes: [
      { id: "needs", kind: "input", eyebrow: "INPUT", title: "Needs + budget", x: 20, y: 151 },
      { id: "primary", kind: "work", eyebrow: "CODEX", title: "Collect primary proof", x: 210, y: 50 },
      { id: "process", kind: "work", eyebrow: "CODEX", title: "Map team workflow", x: 210, y: 252 },
      { id: "filter", kind: "check", eyebrow: "EXACT CHECK", title: "Apply hard filters", x: 400, y: 151 },
      { id: "weights", kind: "human", eyebrow: "CALIBRATE", title: "Lock score weights", x: 590, y: 50 },
      { id: "score", kind: "work", eyebrow: "CODEX", title: "Score shortlist", x: 590, y: 252 },
      { id: "sensitivity", kind: "check", eyebrow: "EXACT CHECK", title: "Test sensitivity", x: 780, y: 50 },
      { id: "recommend", kind: "verify", eyebrow: "DELIVER", title: "Decision memo", x: 780, y: 252 },
    ],
    edges: [
      ["needs", "primary"], ["needs", "process"], ["primary", "filter"], ["process", "filter"],
      ["filter", "weights"], ["weights", "score"], ["score", "sensitivity"], ["sensitivity", "recommend"],
      { from: "sensitivity", to: "weights", kind: "recovery", label: "unstable" },
    ],
    contracts: {
      evidence: "Vendor documentation for every scored capability",
      calibration: "The team sets weights after non-negotiable filters",
      check: "Ranking must survive the agreed sensitivity range",
      recovery: "An unstable result returns to weights, not more browsing",
    },
    result: "The workflow keeps research, business judgment, scoring, and challenge as distinct inspectable decisions.",
  },
  release: {
    tab: "Product release",
    label: "Cross-functional delivery",
    title: "Ship a checkout change without losing the brief",
    task: "Diagnose checkout friction, make the bounded change, preserve instrumentation, and stop if release checks regress.",
    codex: {
      goal: "Improve checkout completion and prepare the release.",
      route: ["Inspect product", "Form a plan", "Implement changes", "Validate result"],
      note: "Codex can iterate deeply, but scope, parallel work, release criteria, and rollback destination remain implicit in the conversation.",
    },
    nodes: [
      { id: "signal", kind: "input", eyebrow: "EVIDENCE", title: "Funnel + recordings", x: 20, y: 151 },
      { id: "diagnose", kind: "work", eyebrow: "CODEX", title: "Diagnose friction", x: 210, y: 151 },
      { id: "scope", kind: "human", eyebrow: "CALIBRATE", title: "Lock release scope", x: 400, y: 50 },
      { id: "ui", kind: "work", eyebrow: "CODEX", title: "Change checkout UI", x: 400, y: 252 },
      { id: "events", kind: "work", eyebrow: "CODEX", title: "Preserve events", x: 590, y: 50 },
      { id: "journey", kind: "check", eyebrow: "EXACT CHECK", title: "Test full journey", x: 590, y: 252 },
      { id: "releasecheck", kind: "check", eyebrow: "EXACT CHECK", title: "Compare baseline", x: 780, y: 50 },
      { id: "release", kind: "verify", eyebrow: "DELIVER", title: "Release notes", x: 780, y: 252 },
    ],
    edges: [
      ["signal", "diagnose"], ["diagnose", "scope"], ["scope", "ui"], ["scope", "events"],
      ["ui", "journey"], ["events", "journey"], ["journey", "releasecheck"], ["releasecheck", "release"],
      { from: "releasecheck", to: "diagnose", kind: "recovery", label: "regression" },
    ],
    contracts: {
      evidence: "Baseline funnel, recordings, and current analytics events",
      calibration: "Product locks the friction point and release boundary",
      check: "Journey, accessibility, event parity, and baseline comparison",
      recovery: "A regression returns to diagnosis before more edits",
    },
    result: "The team can grant broad execution permission while keeping scope and stop conditions visible on the canvas.",
  },
};
