globalThis.WEAVE_WORKFLOWS = Object.freeze({
  finance: {
    label: "Financial analysis",
    title: "Explain a quarterly variance workbook",
    description: "Map source tabs and variance rules in parallel. Management assumptions are fixed before commentary is written, and every reported total must reconcile.",
    result: "CFO brief with a reconciled variance bridge",
    nodes: [
      { id: "brief", x: 28, y: 208, kind: "input", eyebrow: "Goal", title: "Set reporting scope" },
      { id: "workbook", x: 220, y: 82, kind: "work", eyebrow: "Codex", title: "Map workbook" },
      { id: "rules", x: 220, y: 334, kind: "work", eyebrow: "Codex", title: "Define variance rules" },
      { id: "reconcile", x: 414, y: 82, kind: "check", eyebrow: "Exact check", title: "Reconcile source totals" },
      { id: "drivers", x: 414, y: 334, kind: "work", eyebrow: "Codex", title: "Find material drivers" },
      { id: "lock", x: 610, y: 208, kind: "human", eyebrow: "Calibration", title: "Lock assumptions" },
      { id: "bridge", x: 806, y: 82, kind: "work", eyebrow: "Codex", title: "Build variance bridge" },
      { id: "commentary", x: 806, y: 334, kind: "work", eyebrow: "Codex", title: "Draft commentary" },
      { id: "pack", x: 1002, y: 208, kind: "verify", eyebrow: "Review", title: "Audit the CFO pack" },
    ],
    edges: [
      ["brief", "workbook"], ["brief", "rules"], ["workbook", "reconcile"], ["workbook", "drivers"],
      ["rules", "drivers"], ["reconcile", "lock"], ["drivers", "lock"], ["lock", "bridge"],
      ["lock", "commentary"], ["bridge", "pack"], ["commentary", "pack"],
    ],
  },
  campaign: {
    label: "Creative direction",
    title: "Create a launch poster with an image MCP",
    description: "Separate facts from exploration, generate three visual routes through a chosen image connector, lock one route, then audit typography and asset provenance.",
    result: "Production poster, source prompts, and rights notes",
    nodes: [
      { id: "brief", x: 28, y: 208, kind: "input", eyebrow: "Goal", title: "Read campaign brief" },
      { id: "facts", x: 220, y: 82, kind: "work", eyebrow: "Codex", title: "Extract fixed facts" },
      { id: "references", x: 220, y: 334, kind: "work", eyebrow: "Codex", title: "Map visual references" },
      { id: "concepts", x: 414, y: 208, kind: "work", eyebrow: "Image MCP", title: "Generate 3 boards" },
      { id: "choose", x: 610, y: 208, kind: "human", eyebrow: "Calibration", title: "Lock one direction" },
      { id: "art", x: 806, y: 82, kind: "work", eyebrow: "Image MCP", title: "Render artwork" },
      { id: "type", x: 806, y: 334, kind: "work", eyebrow: "Codex", title: "Set type and copy" },
      { id: "facts-check", x: 1002, y: 82, kind: "check", eyebrow: "Exact check", title: "Check facts and size" },
      { id: "review", x: 1002, y: 334, kind: "verify", eyebrow: "Review", title: "Critique final poster" },
    ],
    edges: [
      ["brief", "facts"], ["brief", "references"], ["facts", "concepts"], ["references", "concepts"],
      ["concepts", "choose"], ["choose", "art"], ["choose", "type"], ["art", "facts-check"],
      ["type", "review"], ["facts-check", "review"],
    ],
  },
  crm: {
    label: "Operations strategy",
    title: "Choose a CRM for a 50-person sales team",
    description: "Requirements and vendor evidence are collected separately. The team locks its non-negotiables before scoring, migration planning, and an adversarial recommendation review.",
    result: "Two-option shortlist with evidence and migration risk",
    nodes: [
      { id: "decision", x: 28, y: 208, kind: "input", eyebrow: "Goal", title: "Frame decision" },
      { id: "needs", x: 220, y: 82, kind: "work", eyebrow: "Codex", title: "Map team needs" },
      { id: "vendors", x: 220, y: 334, kind: "work", eyebrow: "Codex", title: "Collect vendor docs" },
      { id: "claims", x: 414, y: 82, kind: "check", eyebrow: "Exact check", title: "Verify cited claims" },
      { id: "tradeoffs", x: 414, y: 334, kind: "work", eyebrow: "Codex", title: "Model tradeoffs" },
      { id: "lock", x: 610, y: 208, kind: "human", eyebrow: "Calibration", title: "Lock requirements" },
      { id: "score", x: 806, y: 82, kind: "work", eyebrow: "Codex", title: "Score shortlist" },
      { id: "migration", x: 806, y: 334, kind: "work", eyebrow: "Codex", title: "Plan migration" },
      { id: "recommend", x: 1002, y: 208, kind: "verify", eyebrow: "Review", title: "Challenge recommendation" },
    ],
    edges: [
      ["decision", "needs"], ["decision", "vendors"], ["vendors", "claims"], ["needs", "tradeoffs"],
      ["claims", "tradeoffs"], ["tradeoffs", "lock"], ["lock", "score"], ["lock", "migration"],
      ["score", "recommend"], ["migration", "recommend"],
    ],
  },
  frontend: {
    label: "Product design",
    title: "Repair a checkout journey",
    description: "Audit evidence and the design system in parallel, compare three routes, lock one route, then catch accessibility and visual drift before release.",
    result: "Implemented checkout with interaction and accessibility evidence",
    nodes: [
      { id: "goal", x: 28, y: 208, kind: "input", eyebrow: "Goal", title: "Set checkout outcome" },
      { id: "funnel", x: 214, y: 82, kind: "work", eyebrow: "Codex", title: "Audit funnel evidence" },
      { id: "system", x: 214, y: 334, kind: "work", eyebrow: "Codex", title: "Audit design system" },
      { id: "routes", x: 400, y: 208, kind: "work", eyebrow: "Codex", title: "Draft 3 routes" },
      { id: "choose", x: 582, y: 208, kind: "human", eyebrow: "Calibration", title: "Lock target route" },
      { id: "shell", x: 760, y: 82, kind: "work", eyebrow: "Codex", title: "Build interface" },
      { id: "states", x: 760, y: 334, kind: "work", eyebrow: "Codex", title: "Build interactions" },
      { id: "a11y", x: 946, y: 82, kind: "check", eyebrow: "Exact check", title: "Run accessibility" },
      { id: "visual", x: 946, y: 334, kind: "verify", eyebrow: "Review", title: "Inspect rendered flow" },
      { id: "release", x: 1128, y: 208, kind: "output", eyebrow: "Result", title: "Release candidate" },
    ],
    edges: [
      ["goal", "funnel"], ["goal", "system"], ["funnel", "routes"], ["system", "routes"],
      ["routes", "choose"], ["choose", "shell"], ["choose", "states"], ["shell", "a11y"],
      ["states", "visual"], ["a11y", "release"], ["visual", "release"],
    ],
  },
});
